name: task-4-workflow
run-name: Task 4 workflow
on:
  pull_request:
    branches:
      - main
    paths:
      - "desktop-app/**"

defaults:
  run:
    working-directory: desktop-app
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: desktop-app
      - name: Install dependencies
        run: npm install
      - name: Run e2e tests
        id: e2e
        run: npm run e2e
      - name: Archive test results
        if: ${{ failure() && steps.e2e.conclusion == 'failure' }}
        uses: actions/upload-artifact@v2
        with:
          name: e2e-test-results
          path: desktop-app/test-results
          retention-days: 7