name: task-2-workflow
run-name: Task 2 workflow
on:
  pull_request:
    branches:
      - main
defaults:
  run:
    working-directory: desktop-app
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: desktop-app
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test
