name: task-6-workflow
run-name: Task 6 workflow
on:
  push

defaults:
  run:
    working-directory: desktop-app
jobs:
  deploy-website:
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: desktop-app
      - name: Install dependencies
        run: npm install
      - name: Build the app
        run: npm run make
      - name: List files
        run: ls
      - name: archive build
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-build
          path: desktop-app/out
          retention-days: 1
